# General Useful Tips {#tips}

## Correct Writing


First of all, I want to start by Titles. It is very important that you know how titles are written properly. You need to title you analysis, visualization, applications, sections, everything correctly. 

Every first letter in a title should be capitalized except for prepositions or connecting words like and, or, the, this. 
If we want to convert the phrase general useful tips to a title it becomes: General Useful Tips. 

Now, also, sentences should be written properly. The first word's first letter should be capital and the sentence should end with a period also called full-stop like this one. 


One great thing I find about R Markdown and knitting a document is that to successfully knit there needs to be zero errors. So this is a great way to check if there is any error in the code.

For working in R Markdown. Please knit the markdown after making small changes in the code so you know if there is an error and can isolate, correct, and debug it. If you write a lot of code and then knit and there is a error, even a very simple error can be very hard to find buried in code. 

Further, once it knits successfully, then the code needs to be immediately committed to git and push it to GitHub.

These two steps of knitting and pushing the code to GitHub should be like breathing. Done extremely often automatically and even without thinking. If you can you should make a short cut like TAB + G so that the the r markdown knits and if successful then commits and pushes to GitHub only prompting you to add a commit message.


