## Folder Organization

Spending a few seconds to properly name your folders and files will help you find your files more quickly later and it will look more professional.
Following are some points you should always keep in mind when creating & organizing folders and files.

**Point 1** Place the document in a single local drive.

**Point 2** Place all the documents related to a single project under a single “root folder”.

**Point 3** Being consistent in naming your folder by following a naming format will make it easier for you identify the correct folder especially if you have different projects of same company at a time. Choose a naming format and stick with it.
e.g. Company Name Project Name Date.

**Point 4** Some operating systems (such as Unix) do not allow spaces in file or folder names, so avoid this if your computing environment is mixed. Instead, use the underscores as a delimiter (e.g. Doe_John_Proposal.doc.) Other characters such as / ? < > \ : * | " ^ are also prohibited in file or folder names under Windows.

**Point 5** Use camel case.

**Point 6** Be descriptive in name but keep it short and logical.  Don't go overboard - file/path names have length limits which vary between operating systems. Under Windows the maximum full path length for a file (e.g. the drive letter + folder names + file name) is 260 characters.

Use common abbreviations wherever possible, such as Jan for January or Corp for Corporation. The goal when naming files is to be able to tell what the file is about without having to open it and look.# Git and Git Hub {#git}

First of all, I would like to say that command line and linux are amazing. It does things so simply and so easily it is almost as if you wave a hand a your room gets cleaned. You make a few hand gestures and wood, stone, and metal come together and assemble themselves into the frame of the house you have in mind. The ratio of the amount of effort you put in, the simplisity of the instructions and the accuracy of the execution to not what you say, but what you actually want is a kin to that of magic. So I write this ode in praise of the command line, Linux, and its predecessor Unix. 


## The Command Line

First please note that for the title the first letter of every word is capital except of connecting words which are not present. Also, since it is a Title it does not end with a peroid also called full-stop. 

Here are the basic commands to be used at the command line or terminal. 

## Essential Command Line Tips

Knowing these tips is essential because it increases productivity by so much and makes this much easier to do. 

1. **Tip Number 1:** When simultaneously working on two different projects, not even necessarily programming projects, then have two terminals or git bash terminals open each one cd'ed into the respepective project's working directory. 

I tend to work on two projects at the same time. This is what I found to be very productive for me. I know if I start becoming less productive i.e. start not having ideas, hit bottle necks, become very slow, then I know I can switch to the other project. Also, when I only have one project open I feel a lot more pressure, that as if I need to finish it or complete it quickly. By having two projects open I experience less stress and don't feel like if I am unable to progress in one then I am stuck. Have two projects open removes the feeling of only having one way forward and the fear of being stuck if that way is blocked. 

So when you have two separate coding projects running and you need to commit and push the changes to the GitHub, the amazing thing is to just have two git bash or terminals open with each being in one project and they run independently of one another. For some applications you cannot have two separate intinces running at the same time doing separate things. 



## How to see which remote repository your local repository is linked to or more explicitely, it is fetching from and pushing to.

Several git command accomplish this, with differing levels of detail. 

The simplest one I find is the following, though it gives a lot of detail.

```{bash, eval=F}
git config -l
```


There is another one with a little less detail:

```{bash, eval=F}
git remote show origin
```


Now the below one gives the minimum information: the fetch and push information.

```{bash, eval=F}
git config -v

```

Finally, there is the command which is the longest in terms of typing out and according to me the hardest to remember, but it gives you the least amount information hence the output is the least verbose.

```{bash, eval=F}
git config --get remote.origin.url

```

Though it is has one drawback that 

Any of the commands with config in them have the added benefit that you do not need to be connected to the internet (more technically accurate and more precise parlance, you do not need to be on a network that can reach the repo where the origin resides.)

### How to name git branches.

Most branches you will create will add some feature to the code. What feature to add will be assigned and described in the jira ticket. Jira ticket will be of the form: CS-150. 

Therefore, the name convention for a branch as above would be like this: feature/CS-150. Please not that the 'f' in feature needs to be lower case - not 'F' like Feature/CS-150.

This is the branch name. Notice, the first thing is what type of edit is being done, followed by forward slash and lastly the jira ticket. 

Other types of code edits could be 'debug' or 'test' instead of feature. Thus, thos branches would be named as follows: debug/CS-150 or test/CS-150


## Git Commands Summary

```{bash eval=FALSE}

#on branches
### Start


# How to clone a repo from GitHub

# Step 0: cd into folder where you want to clone repo.
# Step 1: Open “Git Bash” and change the current working directory to the location where you want the cloned directory.THEN
git clone #{repository URL}
# cd into the repo you just cloned.


# Create new local branch that you will work on. 

After cloning a remote repository to your local drive & before working on it you should create a branch in your local repository with Git Bash. If you don't do that it will create an error called "Merge conflict" with main branch.

# Step 0: Open "Git Bash" in where you cloned the remmote repo.

# Step 1: Type command 
git branch branch_name.

# Step 2: To switch among branches 
git checkout branch_name.

# Step 3: To check in which branch currently working in/list of all branches 
git branch. 


git branch branch_name #creates-new-branch


# Publish branch created in local repo to GitHub repo. 

git push -u origin branch_name #Publishes local branch to remote GitHub branch. 
# Now start work in the folder/directory - repo.
# And always type git status before you type anything else. 


# Add work to local git repo

git add .


# How to commit to the local repo and push to remote repo.

git commit -m "commit_msg" #repo-updation-msg


# Add committed work to remote github repo from local git repo.

git push

### End 


# Repeat from line 111 till End when make more changes like writing more code. 


###########
# Other Git Commands below
###########

git remote add origin https://github.com/sawerasaleemshaikh/___.git 
git branch #shows-all-parent-branches-with pointer-on-current-branch
git branch branch_name #creates-new-branch
git checkout branch_name #switches-to-mentioned-branch
git checkout -b branch_name #creates-&-switches-to-new-mentioned-branch,-if-it-already-exists-then-it-resets-it, on local repo
# Publish branch created in local repo to GitHub repo can also run the same command as above. 
git push -u origin branch_name #Publishes local branch to remote GitHub branch. 
git push -u origin branch_name #pushes-stuff-to-that-branch
# How to initialize a folder/directory and make it a repo.
git init
git add . #add-all
git status #tells-current-branch/status-only
git branch -d branchName #del local branch while being on the develop branch
git branch -D branchName #dont save changes and del local branch git push #when u
git push --delete remoteBranchName localBranchName #delete remote branch
 
#update develop: 
git add .
git commit -m ""
git push
#on main
git push -u origin master
git clone link
git pull #to get up to date with others works
git checkout branch_name #your current opened project will be closed and the one you checkedout will be opened


# Commands to find out which remote repo the local repo is linked to
git config -l
git config -v
git remote show origin
git remote get-url origin

```


If history is making issue, open in vscode and go to extensions number and discard

no push in develop


# Pull Requests

The name of pull request should be the name of the branch, e.g. feature/CS-104. To be explicit it should be first the type of edit: feature, test, debug, followed by forward slash then by the Jira Ticket name.
 
PR Example:

{Add what the description of what was done in the description of the PR. Example below:}

Gauge location changed from beside graph to the top.

{You also need to indicate if your code has any errors, warnings, and if it is working fine. See below:}
No  errors,
No warnings,
App working fine.
