# R Markdown {#rmarkdown}

First of all, I would like to say that markdown is amazing and that R markdown is even more amazing. 


## R markdown general tips for reports.

1. Firstly, when you load tidyverse you do not need to load the different packages contained in tidyverse such as dplyr, ggplot2, readr, tidytext separately. 

2. Secondly, all the libraries or packages should be in the same code chuck loaded in the beginning of the R markdown.

3. 


## Sample paragraph displaying R Markdown capabilities

We describe our methods in this chapter.

Math can be added in body using usual syntax like this 

## math example

$p$ is unknown but expected to be around 1/3. Standard error will be approximated

$$
SE = \sqrt(\frac{p(1-p)}{n}) \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
$$

You can also use math in footnotes like this^[where we mention $p = \frac{a}{b}$].

We will approximate standard error to 0.027[^longnote]

[^longnote]: $p$ is unknown but expected to be around 1/3. Standard error will be approximated

    $$
    SE = \sqrt(\frac{p(1-p)}{n}) \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
    $$

